version: '3'

services:
    postgres:
        image: backend-postgres:latest
        build: postgresql
        ports:
            - "5432:5432"
        networks:
            - backend
        volumes:
            - vol-pg-data:/var/lib/postgresql/data
    
    server:
        image: backend-server:latest
        build: server/
        ports:
            - "10001:10001"
        networks:
            - backend
volumes:
    vol-pg-data:

networks:
    backend:
        driver: "bridge"
